### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by jema28** [foundersandcoders/accessibility-challenge#24]
Many groups had problems with trying to do an audit on their local files.

**Action**: Add a note to make sure a live server is installed in their text editors (maybe add a link to the VS code and atom plugin) and to do the audit on a live server.

**Comment by boi87** [comment]
Charlie and I had the same issue today. We used ** https://surge.sh/** but it might have been better to have it suggested in the workshop instructions.

**Comment by charlielafosse** [comment]
As mentioned above, there are also plugins that you can use from your editor - would be good to together a how-to for plugins and surge if it's needed too and include in the workshop :+1:
