### ISSUE TITLE
Tab-index on solutions branch

### ISSUE THREAD

**Issue by Samatar26** [foundersandcoders/accessibility-challenge#5]
I believe that we should remove all of the tab-index=0 on the HTML elements, because it messes with the page's default behaviour which is tabbing to interactive elements, such as links and buttons. I do agree that we should make them aware of the tab-index attribute, but not in this manner as I think it will cause further confusion as had happened with fac10

**Comment by jsms90** [comment]
`tabindex="0"` seems to be back in the solutions branch and caused more confusion with FAC11, with many groups putting unnecessary `tabindex="0"`s into their projects and messing with the default behaviour again
